import os
import json
import locale
import sys
import reports
import emails

def load_data(filename):
    """Loads the contents of filename as a JSON file."""
    with open(filename) as json_file:
        data = json.load(json_file)
    return data


def format_car(car):
    """Given a car dictionary, returns a nicely formatted name."""
    return "{} {} ({})".format(
        car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
    """Analyzes the data, looking for maximums.

    Returns a list of lines that summarize the information.
    """
    max_revenue = {"revenue": 0}
    max_sales = {"sales": 0}
    max_popular = {}

    for item in data:
        # Calculate the revenue generated by this model (price * total_sales)
        # We need to convert the price from "$1234.56" to 1234.56
        item_price = locale.atof(item["price"].strip("$"))
        item_revenue = item["total_sales"] * item_price
        if item_revenue > max_revenue["revenue"]:
            item["revenue"] = item_revenue
            max_revenue = item
            #print(item)
        # TODO: also handle max sales
        item_sales = item["total_sales"]
        if item_sales > max_sales["sales"]:
            item['sales'] = item_sales
            max_sales = item
        # TODO: also handle most popular car_year
        key = item["car"]["car_year"]
        if key in max_popular:
            max_popular[key] += item["total_sales"]
        else:
            max_popular[key] = item["total_sales"]
    max_value = max(max_popular, key=max_popular.get)
    
    summary = [
        "The {} generated the most revenue: ${}".format(
        format_car(max_revenue["car"]), max_revenue["revenue"]),

        "The {} had the most sales {}".format(
        format_car(max_sales["car"]), max_sales["sales"]),

        "The most pupular year was {} with {} sales".format(max_value, max_popular[max_value])
    ]

    return summary


def cars_dict_to_table(car_data):
    """Turns the data in car_data into a list of lists."""
    table_data = [["ID", "Car", "Price", "Total Sales"]]
    for item in car_data:
        table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
    return table_data


def main(argv):
    """Process the JSON data and generate a full report out of it."""
    data = load_data("car_sales.json")
    summary = process_data(data)
    print(summary)
    info = ""
    for line in summary:
        info += line + '<br/>'
    table = cars_dict_to_table(data)

    # TODO: turn this into a PDF report
    reports.generate('cars.pdf',"Sales summary for last month", info, table)


    # TODO: send the PDF report as an email attachment
    sender = "automation@example.com"
    receiver = "{}@example.com".format(os.environ.get('USER'))
    subject = "Sales summary for last month"
    body = "Check this out"

    message = emails.generate(sender, receiver, subject, body,"/tmp/cars.pdf")
    emails.send(message)

if __name__ == "__main__":
    main(sys.argv)
